spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: orxanrustamov1827@gmail.com
    password: asjoxyxwfvzpncrp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: mailSender
#  datasource:
#    url: jdbc:postgresql://localhost:5432/mailSender
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
server:
  port: 8082
